steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hubspot-notification-app-backend/hubspot-notification-app-backend:$TAG_NAME',
        '.',
      ]

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hubspot-notification-app-backend/hubspot-notification-app-backend:$TAG_NAME',
      ]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/hubspot-notification-app-backend/hubspot-notification-app-backend:$TAG_NAME

options:
  logging: CLOUD_LOGGING_ONLY
